printWidth: 80
tabWidth: 2
useTabs: false
semi: true
singleQuote: true
trailingComma: all
bracketSpacing: true
jsxBracketSameLine: false
arrowParens: avoid
<<<<<<< HEAD
proseWrap: always
=======
proseWrap: always
>>>>>>> 2f3f0f59aabccdce60e84bbec95bb17020d8b796
